site_name: Brainstorm AI
site_description: Système multi-agents pour le brainstorming créatif avec GPT
site_author: Brainstorm AI Team
site_url: https://brainstorm-ai.github.io/

repo_name: brainstorm-ai/brainstorm-ai
repo_url: https://github.com/brainstorm-ai/brainstorm-ai
edit_uri: edit/main/docs/

theme:
  name: material
  language: fr
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Passer en mode sombre
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Passer en mode clair
  
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - content.code.copy
    - content.code.annotate

  icon:
    logo: material/brain
    repo: fontawesome/brands/github

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      lang: fr
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            show_object_full_path: false
            show_category_heading: true
            show_if_no_docstring: false
            show_signature_annotations: true
            show_bases: true
            group_by_category: true
            heading_level: 2

nav:
  - Accueil: index.md
  - Guide de démarrage:
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
    - Premier brainstorm: getting-started/first-brainstorm.md
  - Concepts:
    - Architecture: concepts/architecture.md
    - Les agents: concepts/agents.md
    - Flux de travail: concepts/workflow.md
  - API Reference:
    - Core:
      - Config: api/core/config.md
      - GPT: api/core/gpt.md
      - Loop Manager: api/core/loop_manager.md
      - Types: api/core/types.md
    - Agents:
      - Base Agent: api/agents/base_agent.md
      - Agent Créatif: api/agents/agent_creatif.md
      - Agent Critique: api/agents/agent_critique.md
      - Agent Révision: api/agents/agent_revision.md
      - Agent Score: api/agents/agent_score.md
      - Agent Synthèse: api/agents/agent_synthese.md
      - Agent Application: api/agents/agent_application.md
  - Guides avancés:
    - Optimisation des coûts: advanced/cost-optimization.md
    - Personnalisation des agents: advanced/custom-agents.md
    - Intégration API: advanced/api-integration.md
  - Développement:
    - Contribuer: contributing.md
    - Architecture technique: development/architecture.md
    - Tests: development/testing.md
  - Changelog: changelog.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/brainstorm-ai
    - icon: fontawesome/brands/discord
      link: https://discord.gg/brainstorm-ai
  
  version:
    provider: mike
    default: stable 