# Ce fichier redirige vers la configuration principale
# La vraie configuration est dans config/python/pyproject.toml

[tool.pytest.ini_options]
# Pytest va chercher sa config dans config/python/pytest.ini
addopts = "-c config/python/pytest.ini"

[tool.tox]
# Tox va chercher sa config dans config/python/tox.ini
# Utiliser: tox -c config/python/tox.ini 