version: '3.8'

services:
  brainstorm:
    build:
      context: .
      dockerfile: Dockerfile
    image: brainstorm-ai:latest
    container_name: brainstorm-ai
    restart: unless-stopped
    
    environment:
      # OpenAI API Key - Set this in .env file
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # Optional configuration
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEBUG=${DEBUG:-false}
      - DISABLE_CONFIRMATION=${DISABLE_CONFIRMATION:-false}
      # Model configuration
      - DEFAULT_MODEL=${DEFAULT_MODEL:-gpt-4o}
      - DEFAULT_TEMPERATURE=${DEFAULT_TEMPERATURE:-0.7}
      
    volumes:
      # Persistent data
      - ./logs:/app/logs
      - ./exports:/app/exports
      # Configuration override (optional)
      - ./config.yaml:/app/config.yaml:ro
      # Environment file (if using .env instead of env vars)
      - ./.env:/app/.env:ro
      
    networks:
      - brainstorm-network
      
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
          
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        
    # Security options
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      
  # Optional: Jupyter notebook for interactive exploration
  jupyter:
    image: jupyter/minimal-notebook:latest
    container_name: brainstorm-jupyter
    restart: unless-stopped
    
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      
    volumes:
      - ./:/home/jovyan/work
      - jupyter-data:/home/jovyan
      
    ports:
      - "8888:8888"
      
    networks:
      - brainstorm-network
      
    profiles:
      - dev
      
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''

  # Optional: PostgreSQL for storing brainstorm history
  postgres:
    image: postgres:15-alpine
    container_name: brainstorm-db
    restart: unless-stopped
    
    environment:
      - POSTGRES_USER=brainstorm
      - POSTGRES_PASSWORD=${DB_PASSWORD:-brainstorm}
      - POSTGRES_DB=brainstorm_db
      
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql:ro
      
    ports:
      - "5432:5432"
      
    networks:
      - brainstorm-network
      
    profiles:
      - db
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U brainstorm"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  brainstorm-network:
    driver: bridge

volumes:
  jupyter-data:
  postgres-data: 