# Configuration du système de brainstorming IA
# ============================================

# Configuration générale du brainstorming
general:
  # Objectif principal du brainstorming
  objectif: "CECI EST UN TEST(objectif)"
  
  # Contexte du projet
  contexte: "CECI EST UN TEST(contexte)"
  
  # Contraintes à respecter
  contraintes: "CECI EST UN TEST(contraintes)"
  
  # Nombre de cycles de brainstorming (optimisé : 3-4 cycles suffisent généralement)
  cycles: 1
  
  # Nombre d'idées top à extraire pour l'application (augmenté pour plus d'options)
  top_ideas_count: 1
  
  # Demander confirmation avant de démarrer
  ask_confirmation: true

# Configuration des agents et modèles IA
agents:
  # Modèles GPT optimisés pour performance/coût
  models:
    creatif: "gpt-4o"           # GPT-4o pour créativité maximale et rapidité
    critique: "gpt-4o"          # GPT-4o pour analyse approfondie et précise
    revision: "gpt-4o"          # GPT-4o pour révision de qualité optimale
    synthese: "gpt-4o"          # GPT-4o pour synthèse complexe et structurée
    score: "gpt-4o"             # GPT-4o pour évaluation précise et cohérente
    application: "gpt-4o"       # GPT-4o pour planification détaillée
    default: "gpt-4o"           # GPT-4o comme défaut (meilleur modèle disponible)
  
  # Températures optimisées par rôle
  temperatures:
    creatif: 0.9      # Température élevée pour maximiser la créativité
    critique: 0.4     # Température basse pour analyse précise et factuelle
    revision: 0.6     # Température modérée pour révision équilibrée
    synthese: 0.5     # Température modérée-basse pour synthèse cohérente
    score: 0.2        # Température très basse pour scoring précis
    application: 0.6  # Température modérée pour planification pratique
    default: 0.7      # Température équilibrée par défaut
  
  # Limites de contexte optimisées
  max_context_chars: 150000  # Optimisé pour GPT-4o (jusqu'à 128k tokens)

# Configuration de l'API OpenAI
api:
  # La clé API est lue depuis les variables d'environnement pour la sécurité
  # OPENAI_API_KEY doit être définie comme variable d'environnement système
  # Le système supporte aussi les fichiers .env comme fallback
  
  # Paramètres de retry optimisés pour fiabilité
  max_retries: 5        # Augmenté pour gérer les pics de charge
  retry_delay_base: 1.5 # Délai plus court pour améliorer la réactivité
  
  # Timeout pour les requêtes (optimisé pour GPT-4o)
  request_timeout: 120
  
  # Prix des modèles OpenAI (en dollars par 1000 tokens) - Mis à jour Décembre 2024
  pricing:
    gpt-4o:
      input: 0.0025      # $2.50 per 1K input tokens
      output: 0.01       # $10.00 per 1K output tokens
    gpt-4o-mini:
      input: 0.00015     # $0.15 per 1K input tokens
      output: 0.0006     # $0.60 per 1K output tokens
    gpt-4:
      input: 0.03        # $30.00 per 1K input tokens
      output: 0.06       # $60.00 per 1K output tokens
    gpt-3.5-turbo:
      input: 0.0005      # $0.50 per 1K input tokens
      output: 0.0015     # $1.50 per 1K output tokens

# Configuration des exports et logs
export:
  # Formats d'export optimisés
  formats:
    yaml: true
    json: true      # Activé pour compatibilité avec outils d'analyse
    markdown: true  # Activé pour documentation lisible
  
  # Chemins de sauvegarde
  paths:
    logs_dir: "data/logs"
    exports_dir: "data/exports"
  
  # Nom du fichier de log avec plus d'informations
  log_filename_pattern: "brainstorm_{timestamp}"
  
  # Sauvegarder automatiquement les idées individuelles
  save_individual_ideas: true

# Configuration de l'affichage
display:
  # Utiliser des emojis dans l'affichage console
  use_emojis: true
  
  # Afficher les tokens consommés (important pour optimisation)
  show_token_usage: true
  
  # Emojis optimisés pour meilleure lisibilité
  emojis:
    confirmation: "🧠"
    objectif: "🎯"
    contexte: "📚"
    contraintes: "⚠️"
    cycles: "🔁"
    creatif: "💡"
    critique: "🔍"
    defense: "🛡️"
    replique: "🔄"
    revision: "✏️"
    synthese: "🧠"
    application: "📌"
    success: "✅"
    stats: "📊"
    idea: "💭"      # Nouvel emoji pour les idées
    warning: "⚠️"   # Pour les avertissements
    info: "ℹ️"      # Pour les informations
    start: "🚀"     # Pour le démarrage
    cycle: "🔄"     # Pour les cycles
    export: "💾"    # Pour l'export
  
  # Afficher la barre de progression
  show_progress: true

# Configuration des chemins de prompts personnalisés (optionnel)
# Si définis, ces prompts remplaceront ceux par défaut dans le code
custom_prompts:
  # Laisser vide pour utiliser les prompts par défaut
  # Exemple : 
  # creatif: "prompts/custom_creatif.txt"
  # critique: "prompts/custom_critique.txt"

# Configuration avancée optimisée
advanced:
  # Stratégies d'extraction des idées top (ordre optimisé)
  idea_extraction_strategies:
    - "numbered"    # Priorité aux listes numérotées (plus structuré)
    - "bullet"      # Puis listes avec - (commun)
    - "starred"     # Puis listes avec * 
    - "fallback"    # Fallback en dernier recours
  
  # Validation des scores optimisée
  score_validation:
    min_value: 1        # Min à 1 pour éviter les scores de 0 non informatifs
    max_value: 10
    required_keys: ["impact", "faisabilite", "originalite", "clarte"]
    fallback_value: 6   # Valeur par défaut légèrement positive
  
  # Nouveaux paramètres d'optimisation
  optimization:
    # Détection de redondance entre cycles
    detect_redundancy: true
    
    # Seuil de similarité pour considérer une idée comme redondante (0-1)
    similarity_threshold: 0.8
    
    # Forcer la diversité des idées
    enforce_diversity: true
    
    # Nombre minimum de mots par idée pour qu'elle soit considérée complète
    min_idea_length: 20
    
    # Bonus de scoring pour l'originalité
    originality_bonus: 1.2 