# Configuration du système de brainstorming IA
# ============================================

# Configuration générale du brainstorming
general:
  # Objectif principal du brainstorming
  objectif: "Développer une stratégie de communication efficace pour une auto-entreprise de créations artistiques (figurines en pâte fimo, dessins), afin de générer des vues sur les réseaux sociaux et vendre les créations."
  
  # Contexte du projet
  contexte: "Auto-entrepreneur débutant dans le domaine artistique, avec des créations manuelles uniques (figurines en pâte fimo, illustrations). Recherche d'une approche adaptée aux plateformes comme Instagram, TikTok, Twitch. Besoin de visibilité, d'interaction avec une audience potentielle, et d'un canal de vente performant. BUDGET TRÈS LIMITÉ (moins de 200€), pas de compétences techniques avancées, travail seul depuis chez soi."
  
  # Contraintes à respecter
  contraintes: "BUDGET MAXIMUM 200€ sur 3 mois, temps limité (5-10h/semaine maximum), besoin d'automatiser au maximum avec des outils GRATUITS uniquement, nécessité de contenus engageants adaptés à chaque plateforme (formats courts TikTok, stories Instagram, timelapses Twitch). PAS de compétences en marketing digital, développement web, ou e-commerce. Solutions SIMPLES et IMMÉDIATEMENT APPLICABLES uniquement."
  
  # Nombre de cycles de brainstorming (réduit pour test)
  cycles: 2
  
  # Nombre d'idées top à extraire pour l'application
  top_ideas_count: 2
  
  # Demander confirmation avant de démarrer
  ask_confirmation: true

# Configuration des agents et modèles IA
agents:
  # Modèles GPT optimisés pour performance/coût
  models:
    creatif: "gpt-4o"           # GPT-4o pour créativité maximale et rapidité
    critique: "gpt-4o"          # GPT-4o pour analyse approfondie et précise
    revision: "gpt-4o"          # GPT-4o pour révision de qualité optimale
    synthese: "gpt-4o"          # GPT-4o pour synthèse complexe et structurée
    score: "gpt-4o"             # GPT-4o pour évaluation précise et cohérente
    application: "gpt-4o"       # GPT-4o pour planification détaillée
    default: "gpt-4o"           # GPT-4o comme défaut (meilleur modèle disponible)
  
  # Températures optimisées par rôle
  temperatures:
    creatif: 0.9      # Température élevée pour maximiser la créativité
    critique: 0.4     # Température basse pour analyse précise et factuelle
    revision: 0.6     # Température modérée pour révision équilibrée
    synthese: 0.5     # Température modérée-basse pour synthèse cohérente
    score: 0.2        # Température très basse pour scoring précis
    application: 0.6  # Température modérée pour planification pratique
    default: 0.7      # Température équilibrée par défaut
  
  # Limites de contexte optimisées
  max_context_chars: 150000  # Optimisé pour GPT-4o (jusqu'à 128k tokens)

# Configuration de l'API OpenAI
api:
  # La clé API est lue depuis les variables d'environnement pour la sécurité
  # OPENAI_API_KEY doit être définie comme variable d'environnement système
  # Le système supporte aussi les fichiers .env comme fallback
  
  # Paramètres de retry optimisés pour fiabilité
  max_retries: 5        # Augmenté pour gérer les pics de charge
  retry_delay_base: 1.5 # Délai plus court pour améliorer la réactivité
  
  # Timeout pour les requêtes (optimisé pour GPT-4o)
  request_timeout: 120
  
  # Prix des modèles OpenAI (en dollars par 1000 tokens) - Mis à jour Décembre 2024
  pricing:
    gpt-4o:
      input: 0.0025      # $2.50 per 1K input tokens
      output: 0.01       # $10.00 per 1K output tokens
    gpt-4o-mini:
      input: 0.00015     # $0.15 per 1K input tokens
      output: 0.0006     # $0.60 per 1K output tokens
    gpt-4:
      input: 0.03        # $30.00 per 1K input tokens
      output: 0.06       # $60.00 per 1K output tokens
    gpt-3.5-turbo:
      input: 0.0005      # $0.50 per 1K input tokens
      output: 0.0015     # $1.50 per 1K output tokens

# Configuration des exports et logs
export:
  # Formats d'export optimisés
  formats:
    yaml: true
    json: true      # Activé pour compatibilité avec outils d'analyse
    markdown: true  # Activé pour documentation lisible
  
  # Chemins de sauvegarde
  paths:
    logs_dir: "data/logs"
    exports_dir: "data/exports"
  
  # Nom du fichier de log avec plus d'informations
  log_filename_pattern: "brainstorm_{timestamp}"
  
  # Sauvegarder automatiquement les idées individuelles
  save_individual_ideas: true
  
  # ✨ NOUVELLES OPTIONS DE PRÉSENTATION PROFESSIONNELLE
  project_presentation:
    # Format de nommage des projets exportés
    filename_pattern: "PROJET_{index:02d}_{title_slug}"
    
    # Inclure les métadonnées dans les exports
    include_metadata: true
    
    # Ajouter un résumé exécutif à chaque projet
    include_executive_summary: true
    
    # Créer un index des projets
    create_project_index: true
    
    # Formatage avancé des documents
    advanced_formatting:
      use_professional_headers: true
      include_status_badges: true
      add_priority_indicators: true
      include_readiness_score: true
    
    # Templates de présentation
    templates:
      individual_project: "professional"  # Options: basic, professional, executive
      summary_report: "executive"         # Options: standard, executive, detailed
      project_index: "dashboard"          # Options: simple, dashboard, detailed

# Configuration de l'affichage
display:
  # Utiliser des emojis dans l'affichage console
  use_emojis: true
  
  # Afficher les tokens consommés (important pour optimisation)
  show_token_usage: true
  
  # Emojis optimisés pour meilleure lisibilité
  emojis:
    confirmation: "🧠"
    objectif: "🎯"
    contexte: "📚"
    contraintes: "⚠️"
    cycles: "🔁"
    creatif: "💡"
    critique: "🔍"
    defense: "🛡️"
    replique: "🔄"
    revision: "✏️"
    synthese: "🧠"
    application: "📌"
    success: "✅"
    stats: "📊"
    idea: "💭"      # Nouvel emoji pour les idées
    warning: "⚠️"   # Pour les avertissements
    info: "ℹ️"      # Pour les informations
    start: "🚀"     # Pour le démarrage
    cycle: "🔄"     # Pour les cycles
    export: "💾"    # Pour l'export
  
  # Afficher la barre de progression
  show_progress: true

# Configuration des chemins de prompts personnalisés (optionnel)
# Si définis, ces prompts remplaceront ceux par défaut dans le code
custom_prompts:
  # Laisser vide pour utiliser les prompts par défaut
  # Exemple : 
  # creatif: "prompts/custom_creatif.txt"
  # critique: "prompts/custom_critique.txt"

# Configuration avancée optimisée
advanced:
  # Stratégies d'extraction des idées top (ordre optimisé)
  idea_extraction_strategies:
    - "numbered"    # Priorité aux listes numérotées (plus structuré)
    - "bullet"      # Puis listes avec - (commun)
    - "starred"     # Puis listes avec * 
    - "fallback"    # Fallback en dernier recours
  
  # Validation des scores optimisée
  score_validation:
    min_value: 1        # Min à 1 pour éviter les scores de 0 non informatifs
    max_value: 10
    required_keys: ["impact", "faisabilite", "originalite", "clarte"]
    fallback_value: 6   # Valeur par défaut légèrement positive
  
  # Nouveaux paramètres d'optimisation
  optimization:
    # Détection de redondance entre cycles
    detect_redundancy: true
    
    # Seuil de similarité pour considérer une idée comme redondante (0-1)
    similarity_threshold: 0.8
    
    # Forcer la diversité des idées
    enforce_diversity: true
    
    # Nombre minimum de mots par idée pour qu'elle soit considérée complète
    min_idea_length: 20
    
    # Bonus de scoring pour l'originalité
    originality_bonus: 1.2 