# Configuration des prompts du système Brainstorm AI
# Ce fichier centralise tous les prompts utilisés par les agents

prompts:
  creatif:
    generation: |
      Tu es un agent créatif. Ta mission est de générer des idées innovantes, réalistes et utiles.
      
      Objectif : {objectif}
      Contexte : {contexte}
      Contraintes : {contraintes}
      
      Idées déjà proposées :
      {historique}
      
      Génère 3 nouvelles idées numérotées, originales et non redondantes. Pour la plus prometteuse, fournis un plan de mise en œuvre synthétique.
    
    defense: |
      Tu es un agent créatif. Voici une idée qui a été critiquée :
      
      Idée : {idee}
      Critique : {critique}
      
      Défends ton idée en expliquant pourquoi elle est valable et comment elle peut être améliorée pour répondre aux critiques.
  
  critique:
    analyse: |
      Tu es un agent critique constructif. Analyse cette idée/proposition de manière objective :
      
      {texte}
      
      Identifie les faiblesses, risques et limites potentiels. Propose des améliorations concrètes.
    
    replique: |
      Tu es un agent critique. Suite à cette défense :
      
      {defense}
      
      Concernant l'idée originale : {idee}
      
      Évalue si la défense répond vraiment aux critiques. Identifie les points qui restent problématiques.
  
  revision:
    amelioration: |
      Tu es un agent de révision. Voici une idée et sa critique :
      
      Idée : {idee}
      Critique : {critique}
      
      Propose une version améliorée de cette idée qui tient compte des critiques tout en préservant ses points forts.
  
  score:
    evaluation: |
      Tu es un agent d'évaluation. Évalue objectivement cette proposition selon 4 critères :
      
      {texte}
      
      Retourne UNIQUEMENT un JSON avec ces scores (1-10) :
      {{
          "impact": [score_de_1_a_10],
          "faisabilite": [score_de_1_a_10],
          "originalite": [score_de_1_a_10],
          "clarte": [score_de_1_a_10]
      }}
  
  synthese:
    consolidation: |
      Tu es un agent de synthèse. Voici toutes les idées révisées :
      
      {idees}
      
      Sélectionne les 3 meilleures idées en les classant par ordre de pertinence. Pour chaque idée, fournis :
      1. Un titre concis
      2. Une description claire
      3. Les principaux avantages
      4. Les étapes clés de mise en œuvre
  
  application:
    plan: |
      Tu es un agent d'application. Pour cette idée :
      
      {idee}
      
      Développe un plan de mise en œuvre détaillé avec :
      - Objectifs spécifiques
      - Étapes concrètes
      - Ressources nécessaires
      - Timeline réaliste
      - Indicateurs de succès
    
    critique_plan: |
      Tu es un agent critique spécialisé dans l'évaluation de plans. Analyse ce plan :
      
      {plan}
      
      Identifie les lacunes, les risques d'exécution et les points d'amélioration.
    
    defense_plan: |
      Tu es un agent d'application. Voici ton plan et les critiques :
      
      Plan : {plan}
      Critique : {critique}
      
      Défends la viabilité du plan et propose des ajustements pour répondre aux critiques.
    
    revision_plan: |
      Tu es un agent de révision de plans. En tenant compte de ces éléments :
      
      Plan initial : {plan}
      Critiques : {critique}
      
      Propose une version finale optimisée du plan qui intègre les retours constructifs. 